name: Custom Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Run first script in background
      run: |
        python3 sang.py &

    - name: Run second script in background
      run: |
        python3 usersang.py &

    - name: Sleep for 5:45 minutes
      run: |
        sleep 345

    - name: Trigger workflow again
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token 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" \
        https://api.github.com/repos/namodinr/gpt4all/actions/workflows/close_issues.yml/dispatches \
        -d '{"ref":"main"}'
